package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", schema = "dbo", catalog = "MinimalismShop")
public class Category implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6540698572891108908L;
	private Integer id;
	private Department department;
	private String name;
	private String description;
	@Transient
	private List<GroupProduct> groupProducts = new ArrayList<>();

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	public Category(Department department, String name, String description,
			List<GroupProduct> groupProducts) {
		this.department = department;
		this.name = name;
		this.description = description;
		this.groupProducts = groupProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDepartment")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public List<GroupProduct> getGroupProducts() {
		return this.groupProducts;
	}

	public void setGroupProducts(List<GroupProduct> groupProducts) {
		this.groupProducts = groupProducts;
	}

}
