package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GroupProduct generated by hbm2java
 */
@Entity
@Table(name = "GroupProduct", schema = "dbo", catalog = "MinimalismShop")
public class GroupProduct implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7012525422847302103L;
	private Integer id;
	private Category category;
	private String name;
	private String description;
	private Integer size;
	private int quantity;
	private String imge;
	private int price;
	private Boolean isSpecial;
	private Boolean isLastest;
	@Transient
	private List<PromotionDetail> promotionDetails = new ArrayList<>();
	@Transient
	private List<Product> products = new ArrayList<>();
	@Transient
	private List<ImportDetail> importDetails = new ArrayList<>();

	public GroupProduct() {
	}

	public GroupProduct(String name, int quantity, int price) {
		this.name = name;
		this.quantity = quantity;
		this.price = price;
	}

	public GroupProduct(Category category, String name, String description, Integer size, int quantity,
			String imge, int price, Boolean isSpecial, Boolean isLastest, List<PromotionDetail> promotionDetails,
			List<Product> products, List<ImportDetail> importDetails) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.size = size;
		this.quantity = quantity;
		this.imge = imge;
		this.price = price;
		this.isSpecial = isSpecial;
		this.isLastest = isLastest;
		this.promotionDetails = promotionDetails;
		this.products = products;
		this.importDetails = importDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategory")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "imge")
	public String getImge() {
		return this.imge;
	}

	public void setImge(String imge) {
		this.imge = imge;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "isSpecial")
	public Boolean getIsSpecial() {
		return this.isSpecial;
	}

	public void setIsSpecial(Boolean isSpecial) {
		this.isSpecial = isSpecial;
	}

	@Column(name = "isLastest")
	public Boolean getIsLastest() {
		return this.isLastest;
	}

	public void setIsLastest(Boolean isLastest) {
		this.isLastest = isLastest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupProduct")
	public List<PromotionDetail> getPromotionDetails() {
		return this.promotionDetails;
	}

	public void setPromotionDetails(List<PromotionDetail> promotionDetails) {
		this.promotionDetails = promotionDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupProduct")
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupProduct")
	public List<ImportDetail> getImportDetails() {
		return this.importDetails;
	}

	public void setImportDetails(List<ImportDetail> importDetails) {
		this.importDetails = importDetails;
	}

}
