package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ImportStore generated by hbm2java
 */
@Entity
@Table(name = "ImportStore", schema = "dbo", catalog = "MinimalismShop")
public class ImportStore implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4044494090748388025L;
	private Integer id;
	private User user;
	private Supplier supplier;
	private int dateImport;
	@Transient
	private List<ImportDetail> importDetails = new ArrayList<>();

	public ImportStore() {
	}

	public ImportStore(User user, Supplier supplier, int dateImport) {
		this.user = user;
		this.supplier = supplier;
		this.dateImport = dateImport;
	}

	public ImportStore(User user, Supplier supplier, int dateImport, List<ImportDetail> importDetails) {
		this.user = user;
		this.supplier = supplier;
		this.dateImport = dateImport;
		this.importDetails = importDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSupplier", nullable = false)
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "dateImport", nullable = false)
	public int getDateImport() {
		return this.dateImport;
	}

	public void setDateImport(int dateImport) {
		this.dateImport = dateImport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importStore")
	public List<ImportDetail> getImportDetails() {
		return this.importDetails;
	}

	public void setImportDetails(List<ImportDetail> importDetails) {
		this.importDetails = importDetails;
	}

}
