package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1867311021670829754L;
	private int id;
	private int price;
	private int discount;
	private int idProduct;
	private int idOrder;

	public OrderDetailId() {
	}

	public OrderDetailId(int id, int price, int discount, int idProduct, int idOrder) {
		this.id = id;
		this.price = price;
		this.discount = discount;
		this.idProduct = idProduct;
		this.idOrder = idOrder;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "discount", nullable = false)
	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	@Column(name = "idProduct", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "idOrder", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return (this.getId() == castOther.getId()) && (this.getPrice() == castOther.getPrice())
				&& (this.getDiscount() == castOther.getDiscount()) && (this.getIdProduct() == castOther.getIdProduct())
				&& (this.getIdOrder() == castOther.getIdOrder());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getPrice();
		result = 37 * result + this.getDiscount();
		result = 37 * result + this.getIdProduct();
		result = 37 * result + this.getIdOrder();
		return result;
	}

}
