package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "`Product`", schema = "dbo", catalog = "MinimalismShop")
public class Product implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1234667748821998843L;
	private Integer id;
	private GroupProduct groupProduct;
	private boolean flag;
	public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	@Transient
	private List<OrderDetail> orderDetails = new ArrayList<>();

	public Product() {
	}

	public Product(GroupProduct groupProduct) {
		this.groupProduct = groupProduct;
	}

	public Product(GroupProduct groupProduct, List<OrderDetail> orderDetails) {
		this.groupProduct = groupProduct;
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGroupProduct", nullable = false)
	public GroupProduct getGroupProduct() {
		return this.groupProduct;
	}

	public void setGroupProduct(GroupProduct groupProduct) {
		this.groupProduct = groupProduct;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public List<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(List<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
