package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "`Promotion`", schema = "dbo", catalog = "MinimalismShop")
public class Promotion implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2684207948434331577L;

	private Integer id;
	
	private String starteDate;
	
	private String expiredDate;
	
	private String note;

	@Transient
	private List<PromotionDetail> promotionDetails = new ArrayList<>();

	public Promotion() {
	}

	public Promotion(String starteDate, String expiredDate) {
		this.starteDate = starteDate;
		this.expiredDate = expiredDate;
	}

	public Promotion(String starteDate, String expiredDate, String note,
			List<PromotionDetail> promotionDetails) {
		this.starteDate = starteDate;
		this.expiredDate = expiredDate;
		this.note = note;
		this.promotionDetails = promotionDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "starteDate", nullable = false)
	public String getStarteDate() {
		return this.starteDate;
	}

	public void setStarteDate(String starteDate) {
		this.starteDate = starteDate;
	}

	@Column(name = "expiredDate", nullable = false)
	public String getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(String expiredDate) {
		this.expiredDate = expiredDate;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public List<PromotionDetail> getPromotionDetails() {
		return this.promotionDetails;
	}

	public void setPromotionDetails(List<PromotionDetail> promotionDetails) {
		this.promotionDetails = promotionDetails;
	}

}
