package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromotionDetail generated by hbm2java
 */
@Entity
@Table(name = "PromotionDetail", schema = "dbo", catalog = "MinimalismShop")
public class PromotionDetail implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2825792497800155823L;
	private Integer id;
	private GroupProduct groupProduct;
	private Promotion promotion;
	private Integer discount;
	private String code;

	public PromotionDetail() {
	}

	public PromotionDetail(GroupProduct groupProduct, Promotion promotion) {
		this.groupProduct = groupProduct;
		this.promotion = promotion;
	}

	public PromotionDetail(GroupProduct groupProduct, Promotion promotion, Integer discount, String code) {
		this.groupProduct = groupProduct;
		this.promotion = promotion;
		this.discount = discount;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGroupProduct", nullable = false)
	public GroupProduct getGroupProduct() {
		return this.groupProduct;
	}

	public void setGroupProduct(GroupProduct groupProduct) {
		this.groupProduct = groupProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPromotion", nullable = false)
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@Column(name = "discount")
	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
