package com.minimalism.shop.entities;
// Generated Jul 14, 2017 8:54:07 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "`Role`", schema = "dbo", catalog = "MinimalismShop")
public class Role implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2166409666498604738L;
	private Integer id;
	private String role;
	private List<User> users = new ArrayList<>();

	public Role() {
	}

	public Role(String role) {
		this.role = role;
	}

	public Role(String role, List<User> users) {
		this.role = role;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "role", nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

}
