package com.minimalism.shop.entities;
// Generated Jul 11, 2017 9:54:23 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "`Supplier`", schema = "dbo", catalog = "MinimalismShop")
public class Supplier implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8489608193571899731L;
	
	private Integer id;
	
	private String name;
	
	private String mail;
	
	private double phone;
	
	private String address;
	
	@Transient
	private List<ImportStore> importStores = new ArrayList<>();

	public Supplier() {
	}

	public Supplier(String name, String mail, double phone, String address) {
		this.name = name;
		this.mail = mail;
		this.phone = phone;
		this.address = address;
	}

	public Supplier(String name, String mail, double phone, String address,
			List<ImportStore> importStores) {
		this.name = name;
		this.mail = mail;
		this.phone = phone;
		this.address = address;
		this.importStores = importStores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mail", nullable = false)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "phone", nullable = false, precision = 53, scale = 0)
	public double getPhone() {
		return this.phone;
	}

	public void setPhone(double phone) {
		this.phone = phone;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public List<ImportStore> getImportStores() {
		return this.importStores;
	}

	public void setImportStores(List<ImportStore> importStores) {
		this.importStores = importStores;
	}

}
